# server port
server.port=8761

# Indicates that this instance should not register itself with the Eureka server
# (since this is the Eureka server itself, it doesn't need to register)
eureka.client.register-with-eureka=false

# Indicates that this instance should not fetch the registry information from the Eureka server
# (since this is the Eureka server itself, it doesn't need to fetch registry)
eureka.client.fetch-registry=false

# The URL where the Eureka server is located
# This is used by Eureka clients to register and discover services
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# The hostname where the Eureka server instance is running
# This is used by clients to connect to this specific Eureka server instance
eureka.instance.hostname=localhost
